/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--border))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        'on-secondary-container': '#596373',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#191c1e',
        'primary-fixed-dim': '#61de8a',
        tertiary: '#5c5f60',
        outline: '#6d7a6e',
        'surface-variant': '#dce3f0',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#121c2a',
        'tertiary-fixed-dim': '#c5c6c8',
        'on-surface-variant': '#3d4a3f',
        'on-primary-fixed-variant': '#005228',
        'outline-variant': '#bccabc',
        'primary-fixed': '#7efba4',
        'on-error': '#ffffff',
        'secondary-container': '#d6e0f3',
        secondary: '#555f6f',
        surface: '#f8f9ff',
        'inverse-surface': '#2a313b',
        'surface-container-highest': '#dce3f0',
        'surface-container-high': '#e2e8f5',
        'on-secondary': '#ffffff',
        'on-primary-container': '#00391a',
        'primary-container': '#27ae60',
        'inverse-on-surface': '#eaf1fe',
        'on-primary-fixed': '#00210c',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#151c25',
        'surface-container': '#e7eefb',
        'on-tertiary': '#ffffff',
        'on-surface': '#151c25',
        error: '#ba1a1a',
        'surface-container-low': '#eef4ff',
        'on-secondary-fixed-variant': '#3d4756',
        'tertiary-fixed': '#e1e2e4',
        'secondary-fixed': '#d9e3f6',
        'secondary-fixed-dim': '#bdc7d9',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#d4dae7',
      },
      spacing: {
        base: '4px',
        gutter: '24px',
        xl: '56px',
        md: '28px',
        lg: '40px',
        sm: '20px',
        margin: '32px',
        xs: '12px',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        arabic: ['Noto Kufi Arabic', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'title-lg': ['20px', { lineHeight: '1.5', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['12px', { lineHeight: '1', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '1', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
